### ISSUE TITLE
with rowreoder while dragging a row , rows are not completely scrolling upto last row

### ISSUE THREAD

**Issue by Kranthi32** [DataTables/RowReorder#29] opened 2023-06-19 15:03 UTC
Dear Team,
I am using row reorder with draging . while dragging the rows unable to scoll completely down up to last row in the page. i tried this roworder with scroller plugin also its not working please find my configuration. please provide solution with rowreoder only.

"bDestroy": true,
        "bDestroy": true,
        "bPaginate": true,
        "bInfo": true,
        'iDisplayLength': 10,
        'scrollCollapse': true,
        'scroller': true,
        rowReorder: {
            'selector': '.dragable',
            'update': false
        },

**Comment by AllanJard** [comment] 2023-06-19 15:04
Hi,

Can you give a link to a test case showing the issue please?

**Comment by Kranthi32** [comment] 2023-06-20 07:39
Hi,
Please find link.

https://onecompiler.com/html/3zc56e75c

**Comment by AllanJard** [comment] 2023-06-20 10:43
Sorry, I hadn't clicked that you have `scroller: true` for this table. As you'll have seen in #14 this is a known issue, and I've just noted there, RowReorder and Scroller, when reordering past the current scroll buffer is not compatible, nor do I think can it be made compatible. Sorry.

Closing as a duplicate of #14, although happy to continue discussing alternatives here.

**Closed as completed by AllanJard** 2023-06-20 10:43 UTC
